options {
    directory "/var/named";
    listen-on port 53 { any; };
    allow-query { any; };
    recursion no;
};

zone "kbvsm.com" IN {
    type master;
    file "/var/named/kbvsm.com.zone";
    allow-update { none; };
};
